Initial attempt at function5 tests before implementation
UBC-MDS/pygtracker pull request #34
Opened 2021-03-03 04:08 UTC by jraza19

2021-03-03 04:18 UTC, tdkhanhvu requested changes

2021-03-03 04:18 UTC, tdkhanhvu commented on tests/test_pygtracker.py
> +def test_number_of_students():
function name should be

test_functiontotest_conditionthatyoutest
```suggestion
def test_ranks_students_num_of_students_match():
```

2021-03-03 04:18 UTC, tdkhanhvu commented on tests/test_pygtracker.py
> +def test_course_input():
```suggestion
def test_rank_students_course_input_not_exist():
```

2021-03-03 04:18 UTC, tdkhanhvu commented on tests/test_pygtracker.py
> +def test_df_equal():
the test needs to have the real output to compare against. It is okay to write just a few tests first (that you expect to run and give you the output that matches what you expected)

2021-03-03 04:18 UTC, tdkhanhvu commented on tests/test_pygtracker.py
> +def test_df_columns():
It's better to run the rank_students() once, assign to a variable, and then call that variable 3 times

student_ranks = gradetracker.rank_students(course_id="511", n=1)
assert rank.columns[0] == ....

2021-03-03 04:18 UTC, tdkhanhvu commented on tests/test_pygtracker.py
> +def test_df_columns():
```suggestion
def test_rank_students_columns_names_match():
```

2021-03-04 06:48 UTC, jraza19 commented
Closing this issue as there has been a new PR (#39) made with the changes to reflect this.

2021-03-04 06:48 UTC, closed without merging