add first 2 fn and tests
UBC-MDS/pygtracker pull request #40
Opened 2021-03-04 08:52 UTC by jianructose

Hi team, I have added tests and first 2 fns. It passed tests on my side. lmk if not on yours.

2021-03-04 08:56 UTC, jianructose commented
#10

2021-03-04 19:12 UTC, tdkhanhvu requested changes
- Merge the code from the main
- Rename the test function to better reflect what we are testing
- Write a helper function to help you generate the dummy data
- Should include test cases to show that the courses and grades are recorded correctly. Currently I only see the failure cases

2021-03-04 19:12 UTC, tdkhanhvu commented on pygtracker/pygtracker.py
> +        assessment_list = ['lab1', 'lab2', 'lab3', 'lab4', 'milestone1', 'milestone2', 'milestone3', 'milestone4', 'feedback', 'quiz1', 'quiz2']
I think limiting the assessment to this list alone is quite rigid as you may have other assessment components as well. But given the scope of this project, you may want to leave it like this.

2021-03-04 19:12 UTC, tdkhanhvu commented on pygtracker/pygtracker.py
> +        for _, w in df.weight.items():
**Suggestions only**
You can optimize this in the vectorization manner, sth similar to this:

(df.weight < 0 or df.weight > 1).sum()

if the result returns > 1 it means one of the component violates the rule. I'm not sure about the syntax though.

2021-03-04 19:12 UTC, tdkhanhvu commented on pygtracker/pygtracker.py
> +        for course_id, sum_weight in df.groupby('course_id').sum('weight').weight.items():
similar as above for the vectorization

2021-03-04 19:12 UTC, tdkhanhvu commented on pygtracker/pygtracker.py
> +        if not set(input_courses).issubset(course_list):
If these are repeated, it is better to extract them to helper function. sth like

**check_if_course_not_exist**

2021-03-04 19:12 UTC, tdkhanhvu commented on pygtracker/pygtracker.py
> +        assessment_list = ['lab1', 'lab2', 'lab3', 'lab4', 'milestone1', 'milestone2', 'milestone3', 'milestone4', 'feedback', 'quiz1', 'quiz2']
If these are repeated, it is better to extract them to helper function. sth like

**check_if_assessment_not_exist**

2021-03-04 19:12 UTC, tdkhanhvu commented on tests/test_pygtracker.py
> +    df['course_id']=[555]
It is better to declare a separate helper function to generate the df frame that you are using here.

`def generate_df_register_courses(course_id, assessment_id, weight)`

2021-03-04 19:12 UTC, tdkhanhvu commented on tests/test_pygtracker.py
> +def test_register_courses_course_id_valid():
```suggestion
def test_register_courses_course_id_invalid():
```

2021-03-04 19:12 UTC, tdkhanhvu commented on tests/test_pygtracker.py
> +def test_register_courses_assess_valid():
```suggestion
def test_register_courses_assess_invalid():
```

2021-03-04 19:12 UTC, tdkhanhvu commented on tests/test_pygtracker.py
> +def test_register_courses_weight_valid_1():
```suggestion
def test_register_courses_weight_invalid_not_sum_to_one():
```

2021-03-04 19:12 UTC, tdkhanhvu commented on tests/test_pygtracker.py
> +def test_register_courses_weight_valid_2():
```suggestion
def test_register_courses_weight_invalid_negative():
```

2021-03-04 19:12 UTC, tdkhanhvu commented on tests/test_pygtracker.py
> +def test_record_grades_course_id_valid():
```suggestion
def test_record_grades_course_id_invalid():
```

2021-03-04 19:12 UTC, tdkhanhvu commented on tests/test_pygtracker.py
> +def test_record_grade_assess_valid():
```suggestion
def test_record_grade_assess_invalid():
```

2021-03-04 19:12 UTC, tdkhanhvu commented on tests/test_pygtracker.py
> +def test_record_grade_grade_valid():
```suggestion
def test_record_grade_grade_invalid_negative():
```

2021-03-05 02:30 UTC, jianructose commented on pygtracker/pygtracker.py
> +        for _, w in df.weight.items():
yep agree. i was on vectorization but realize might be some limitations on this

2021-03-05 03:25 UTC, tdkhanhvu approved these changes

2021-03-05 03:25 UTC, tdkhanhvu commented on tests/test_pygtracker.py
> +    df['grade']=[100.1, -77, 99, 88.4]
It is better to split this into 2 separate tests:
- above 100
- negative

2021-03-05 03:25 UTC, merged